### PR TITLE
Modify sql component to use the proper Ada style UTC conversion

### PR DESCRIPTION
**Pull request by Richard-Wai**
Previously, sql/gnatcoll-sql_impl.adb used older UTC_Time_Offset's from GNAT-specific library packages that returned a Time value. This is not compatible with newer versions of FSF GNAT (9.2.0 in this case).

Updated the two locations in that file to use Ada.Calendar.Time_Zones.UTC_Time_Offset instead.

Builds ok on FreeBSD 12.1, FSF GNAT 9.2.0

### CODE REVIEW

**Comment by anisimkov** [comment]
Richard, Did you see the

**Comment by Richard-Wai** [comment]
This change was the result of the compilation failed. It may be possible that the gnatcoll-core I was using was not up to date enough. I will try that again.

On a philosophical note, however, I can't see how it is ever a better idea to not use the Ada standard library when it has the available facilities.

**Comment by anisimkov** [comment]
The better idea is in reusable code. Do not repeat "* 60" everywhere when we need to shift time to timezone. The GNATCOLL-DB is depend on GNATCOLL-Core and GNATCOLL-Core have to be up to date.

**Comment by Richard-Wai** [comment]
That is the method suggested in the Ada Reference Manual.

**Comment by anisimkov** [comment]
And GNATCOLL-Core uses this method once in own routine.
